config/routes.rb
Realstartupjobs::Application.routes.draw do

  resources :press_mentions

  resources :presses

  resources :jobs_tags

  resources :skill_tags

  ActiveAdmin.routes(self)

  resources :scrapers
  resources :admin

  resources :scraped_jobs

  resources :saved_companies
  resources :home

  resources :saved_jobs

  resources :hidden_jobs

  resources :categories

  devise_for :users

  resources :tags
  resources :jobs do
    collection do 
     get "search"
    end
  end
  resources :companies

  root :to => "home#index"

end

app/models/jobs_tag.rb
class JobsTag < ActiveRecord::Base
  attr_accessible :job_id, :tag_id
end

app/controllers/jobs_tags_controller.rb
class JobsTagsController < InheritedResources::Base
class JobTagsController < InheritedResources::Base
 def index
    @job_tags = JobTag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @job_tags }
    end
  end

  # GET /job_tags/1
  # GET /job_tags/1.json
  def show
    @job_tag = JobTag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @job_tag }
    end
  end

  # GET /job_tags/new
  # GET /job_tags/new.json
  def new
    @job_tag = JobTag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @job_tag }
    end
  end

  # GET /job_tags/1/edit
  def edit
    @job_tag = JobTag.find(params[:id])
  end

  # POST /job_tags
  # POST /job_tags.json
  def create
    @job_tag = JobTag.new(params[:job_tag])

    respond_to do |format|
      if @job_tag.save
        format.html { redirect_to @job_tag, :notice => 'Hidden job was successfully created.' }
        format.json { render :json => @job_tag, :status => :created, :location => @job_tag }
      else
        format.html { render :action => "new" }
        format.json { render :json => @job_tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /job_tags/1
  # PUT /job_tags/1.json
  def update
    @job_tag = JobTag.find(params[:id])

    respond_to do |format|
      if @job_tag.update_attributes(params[:job_tag])
        format.html { redirect_to @job_tag, :notice => 'Hidden job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @job_tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /job_tags/1
  # DELETE /job_tags/1.json
  def destroy
    @job_tag = JobTag.find(params[:id])
    @job_tag.destroy

    respond_to do |format|
      format.html { redirect_to job_tags_url }
      format.json { head :no_content }
    end
  end
end


end

app/helpers/jobs_tags_helper.rb
module JobsTagsHelper
end

app/views/jobs_tags/_form.html.erb
<%= simple_form_for(@jobs_tag) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :tag_id %>
    <%= f.input :job_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jobs_tags/edit.html.erb
<h1>Editing jobs_tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @jobs_tag %> |
<%= link_to 'Back', jobs_tags_path %>

app/views/jobs_tags/index.html.erb
<h1>Listing jobs_tags</h1>

<table>
  <tr>
    <th>Tag</th>
    <th>Job</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs_tags.each do |jobs_tag| %>
  <tr>
    <td><%= jobs_tag.tag_id %></td>
    <td><%= jobs_tag.job_id %></td>
    <td><%= link_to 'Show', jobs_tag %></td>
    <td><%= link_to 'Edit', edit_jobs_tag_path(jobs_tag) %></td>
    <td><%= link_to 'Destroy', jobs_tag, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Jobs tag', new_jobs_tag_path %>

app/views/jobs_tags/new.html.erb
<h1>New jobs_tag</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_tags_path %>

app/views/jobs_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tag:</b>
  <%= @jobs_tag.tag_id %>
</p>

<p>
  <b>Job:</b>
  <%= @jobs_tag.job_id %>
</p>


<%= link_to 'Edit', edit_jobs_tag_path(@jobs_tag) %> |
<%= link_to 'Back', jobs_tags_path %>