config/routes.rb
Realstartupjobs::Application.routes.draw do

  resources :press_mentions

  resources :presses

  resources :jobs_tags

  resources :skill_tags

  ActiveAdmin.routes(self)

  resources :scrapers
  resources :admin

  resources :scraped_jobs

  resources :saved_companies
  resources :home

  resources :saved_jobs

  resources :hidden_jobs

  resources :categories

  devise_for :users

  resources :tags
  resources :jobs do
    collection do 
     get "search"
    end
  end
  resources :companies

  root :to => "home#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  has_many :saved_companies, :dependent => :destroy
  has_many :jobs, :dependent => :destroy 
  #\has_many :saved_jobs
  has_many :company_tags
  has_many :tags, :through => :company_tags
  attr_protected
  #before_validation :download_profile_pic

  has_attached_file :logo, :styles => {:thumb => 'x100', :croppable => '600x600>', :big => '1000x1000>'}

  def funding_string
    return nil if funding.nil?
    if funding > 1000000
      
      '$' + (funding / 1000000.0).to_s + 'M'
    elsif funding > 1000
      '$' + (funding / 1000.0).to_s + 'K'
    else
      '$' + funding.to_s
    end
  end
  
 # def blog_url 
  #  Crunchbase::Company.get(crunchbase_slug).blog_url
#end
 
  def blog_feed_url 
    if Crunchbase::Company.get(crunchbase_slug).blog_feed_url.nil?
      " "
    else
      Crunchbase::Company.get(crunchbase_slug).blog_feed_url
    end
  end
  
  def number_of_employees 
    if Crunchbase::Company.get(crunchbase_slug).number_of_employees.nil?
      employees
    else
      Crunchbase::Company.get(crunchbase_slug).number_of_employees
    end
  end
  
  def company_overview
  #  if Crunchbase::Company.get(crunchbase_slug).overview.nil?
   #   overview
    #else
      Crunchbase::Company.get(crunchbase_slug).overview
    #end
  end
  
  def twitter_url
     "http://www.twitter.com/"+Crunchbase::Company.get(crunchbase_slug).twitter_username
  end
  def image_url_large
    crunchbase_stem = "http://www.crunchbase.com/"
    
   crunchbase_stem + Crunchbase::Company.get(crunchbase_slug).image['available_sizes'][2][1]    
  end
  def image_url_medium
    Crunchbase::Company.get(crunchbase_slug).image['available_sizes'][1][1]    
  end
  def image_url_small
    Crunchbase::Company.get(crunchbase_slug).image['available_sizes'][0][1]    
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.includes(:jobs).all
      if !user_signed_in?
      else
      @user = current_user

      @saved_jobs = SavedJob.where(:user_id => current_user.id)
      @saved_companies = SavedCompany.where(:user_id => current_user.id)
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, :notice => 'Company was successfully created.' }
        format.json { render :json => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.json { render :json => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, :notice => 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= @company.why_us 
 image_tag Crunchbase::Company.get(@company.why_us).image	%>

<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name 
	%>
    <%= f.text_field :name %>
  </div>
  <div class="field>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :funding %><br />
    <%= f.number_field :funding %>
  </div>
  <div class="field">
    <%= f.label :employees %><br />
    <%= f.number_field :employees %>
  </div>
  <div class="field">
  	<%= f.label :hiring %>
  	<%= f.check_box :hiring %>
  </div>
	<div class="field">
		<%= f.label :jobs_url %>
		<%= f.text_field :jobs_url %>
	</div>
	<div class="field">
		<%= f.label :overview %>
		<%= f.text_field :overview %>
	</div>
	<div class="field">
		<%= f.label :crunchbase %>
		<%= f.check_box :crunchbase %>
	</div>
	<div class="field">
		<%= f.label :founded %>
		<%= f.text_field :founded %>
	</div>
	<div class="field">
		<%= f.label :twitter_name %>
		<%= f.text_field :twitter_name %>
	</div>
	<div class"field">
		<%= f.label :blog_url %>
		<%= f.text_field :blog_url %>
	</div>
	<div class="category">
		<%= f.label :category %>
		<%= f.text_field :category %>
	</div>
	<div class="field">
		<%= f.label :crunchbase_url %>
		<%= f.text_field :crunchbase_url %>
	</div>
	<div class="field">
		<%= f.label :logo %>
		<%= f.file_field :logo %>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/_table.html.erb
<div class="span7" style="margin-right: 20px;">
	<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-condensed" id="companytable">
  	<thead>
  		<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Funding</th>
		<th>Founded</th>
		<th>Employees</th>
		<th># Jobs</th>
			<th>Save Company</th>
		</tr>
  	</thead>

	<tbody>
		<% @companies.each do |company | %>
			<tr>
  				<td><%= link_to company.name, company %></td>
				<td><%= company.description %></td>
				<td><%= company.funding_string %></td>
				<td><%= company.founded %></td>
				<td><%= company.employees %></td>
				<td><%= company.jobs.count %></td>

						<td>				<% if  user_signed_in?  %>
<%=
					button_to 'save company', saved_companies_path(company_id: company, user_id: current_user.id  ) %>				<%	else 
						
					end  %>
</td>
			</tr>

		<% end  %>
	</tbody>
	<tfoot style="display:none;">
		<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Funding</th>
		<th>Founded</th>
		<th>Employees</th>
		<th># Jobs</th>
			<th>Save Company</th>
		</tr>
	</tfoot>	
</table>
</div>

app/views/companies/edit.html.erb
<h1>Editing company</h1>
<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div class="span12">
<div class="row">
  <div class="span4">
    <div class="row">
      <div class="span3 well">
        <h3> Filter Companies </h3>
    <form class="form-inline mini" style="margin-bottom: 0px;">
          <fieldset>
            <div class="row">
              <div class="span3">
                <div class="control-group">
                  <label for="companyFilter" class="control-label"><h4>by name</h4></label>
                  <div class="controls">
                    <p id="companyFilter"></p>
                  </div>
                </div>  
              </div>
            </div>
            <div class="row">
              <div class="span3">
                <div class="control-group">
                  <label for="employeeFilter" class="control-label"><h4>by # employees</h4></label>
                  <div class="controls">
                    <p id="employeeFilter"></p>
                  </div>
                </div>  
              </div>
            </div>
            <div class="row">
              <div class="span3">
                <div class="control-group">
                  <label for="foundedFilter" class="control-label"><h4>by year founded</h4></label>
                  <div class="controls">
                    <p id="foundedFilter"></p>
                  </div>
                </div>  
              </div>
            </div>
          </fieldset>
        </form>      </div>
    </div>
  </div>

  <div class="span8">
  	<h1>Listing companies</h1>
  	<%= render 'table' %>
  </div>
</div>
</div>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="span12">
	<span class="center-align">
  <h2><%= @company.name %></h2><p>

</img>
</span>
</p>

</div>
<div class="span6">
<table id="companystats" class="table table-striped table-bordered" >
	<tr>
		<td> <b>Founded</b></td>
		<td><%= @company.founded %></td>
	</tr>
	<tr>
		<td> <b>Employees</b></td>
		<td><%= @company.number_of_employees %></td>
	</tr>
	<tr>
		<td><b>Funding</b></td>
		<td><%= @company.funding_string %></td>
	</tr>
	<tr>
		<td><b>Website</b></td>
		<td><%= link_to  @company.name+" Site", @company.url %><br>
	  </td>
	</tr>
	<tr>
		<td><b>Jobs page:</b></td>
	  <td><%= link_to @company.name+" Job Page", @company.jobs_url %><br></td>
	</tr>
	<tr><td><b>Twitter</td>
		<td> <%= link_to "twitter", @company.twitter_url %></td>
		</tr>
	  
 </table>

</div>
<div class="span6">
	<p>
  		<h2>Overview</h2>
  		<%= raw @company.company_overview %>
	</p>
			<%= link_to 'Back', companies_path %>

</div>
<div class="row">
	<div class="span6">
		</div>
	<div class="span2">
	</div>
	<div class="span4">
	</div>
		<% link_to 'Edit', edit_company_path(@company) %> |
		
</div>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered span8" id="table">
	<thead>
		<tr>
			<th>Job Title</th > 
			<th>Type</th>
			<th>Techie Only?</th>
			<th>Created at</th>
			<th>Save</th>
		</tr>
	</thead>
	<tbody>
		<% @company.jobs.each do |job| %>
			<tr>
				
				<td><%= job.id %> <a href='<%= job.url %>'> <%= job.title %></a></td>
				<td><%= if job.internship == true
					"Internship"
				else 
					"Job"
				end
						 %></td>
				<td><%= if job.technical == true 
					 	"Technical"
					else
						"Not"
						end %></td>
							<td><%= time_ago_in_words(job.created_at) %> ago</td>

				<td><%= if  user_signed_in?  
					button_to 'save job', saved_jobs_path(job_id: job, user_id: current_user  )
					else 
						 "sign in to save jobs" 
					end %></td>
			
			</tr>
		<% end %>

	</tbody>
	<tfoot style="display:none;">
		<tr>
			<th>Job Title</th > 
			<th>Type</th>
			<th>Techie Only?</th>
			<th>Company</th>
			<th>Founded</th>
			<th># of ppl</th>
			<th>VC</th>
			<th>Save</th>
		</tr>
	</tfoot>
</table>