config/routes.rb
Realstartupjobs::Application.routes.draw do

  resources :press_mentions

  resources :presses

  resources :jobs_tags

  resources :skill_tags

  ActiveAdmin.routes(self)

  resources :scrapers
  resources :admin

  resources :scraped_jobs

  resources :saved_companies
  resources :home

  resources :saved_jobs

  resources :hidden_jobs

  resources :categories

  devise_for :users

  resources :tags
  resources :jobs do
    collection do 
     get "search"
    end
  end
  resources :companies

  root :to => "home#index"

end

app/models/hidden_job.rb
class HiddenJob < ActiveRecord::Base
  attr_accessible :job_id, :user_id
end

app/controllers/hidden_jobs_controller.rb
class HiddenJobsController < ApplicationController
  # GET /hidden_jobs
  # GET /hidden_jobs.json
  def index
    @hidden_jobs = HiddenJob.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @hidden_jobs }
    end
  end

  # GET /hidden_jobs/1
  # GET /hidden_jobs/1.json
  def show
    @hidden_job = HiddenJob.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @hidden_job }
    end
  end

  # GET /hidden_jobs/new
  # GET /hidden_jobs/new.json
  def new
    @hidden_job = HiddenJob.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @hidden_job }
    end
  end

  # GET /hidden_jobs/1/edit
  def edit
    @hidden_job = HiddenJob.find(params[:id])
  end

  # POST /hidden_jobs
  # POST /hidden_jobs.json
  def create
    @hidden_job = HiddenJob.new(params[:hidden_job])

    respond_to do |format|
      if @hidden_job.save
        format.html { redirect_to @hidden_job, :notice => 'Hidden job was successfully created.' }
        format.json { render :json => @hidden_job, :status => :created, :location => @hidden_job }
      else
        format.html { render :action => "new" }
        format.json { render :json => @hidden_job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hidden_jobs/1
  # PUT /hidden_jobs/1.json
  def update
    @hidden_job = HiddenJob.find(params[:id])

    respond_to do |format|
      if @hidden_job.update_attributes(params[:hidden_job])
        format.html { redirect_to @hidden_job, :notice => 'Hidden job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @hidden_job.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hidden_jobs/1
  # DELETE /hidden_jobs/1.json
  def destroy
    @hidden_job = HiddenJob.find(params[:id])
    @hidden_job.destroy

    respond_to do |format|
      format.html { redirect_to hidden_jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hidden_jobs_helper.rb
module HiddenJobsHelper
end

app/views/hidden_jobs/_form.html.erb
<%= form_for(@hidden_job) do |f| %>
  <% if @hidden_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hidden_job.errors.count, "error") %> prohibited this hidden_job from being saved:</h2>

      <ul>
      <% @hidden_job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :job_id %><br />
    <%= f.number_field :job_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hidden_jobs/edit.html.erb
<h1>Editing hidden_job</h1>

<%= render 'form' %>

<%= link_to 'Show', @hidden_job %> |
<%= link_to 'Back', hidden_jobs_path %>

app/views/hidden_jobs/index.html.erb
<h1>Listing hidden_jobs</h1>

<table>
  <tr>
    <th>User</th>
    <th>Job</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hidden_jobs.each do |hidden_job| %>
  <tr>
    <td><%= hidden_job.user_id %></td>
    <td><%= hidden_job.job_id %></td>
    <td><%= link_to 'Show', hidden_job %></td>
    <td><%= link_to 'Edit', edit_hidden_job_path(hidden_job) %></td>
    <td><%= link_to 'Destroy', hidden_job, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hidden job', new_hidden_job_path %>

app/views/hidden_jobs/new.html.erb
<h1>New hidden_job</h1>

<%= render 'form' %>

<%= link_to 'Back', hidden_jobs_path %>

app/views/hidden_jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @hidden_job.user_id %>
</p>

<p>
  <b>Job:</b>
  <%= @hidden_job.job_id %>
</p>


<%= link_to 'Edit', edit_hidden_job_path(@hidden_job) %> |
<%= link_to 'Back', hidden_jobs_path %>